$ANSIBLE_VAULT;1.1;AES256
34613163613335666535353535306538663531363838373233376435343139616263373566373538
6336353735663938316634363130336365616261363465320a646135323662626564646535303935
31656233396661633731663066616664336565633933313164323835383037616131333738396437
3763343564326431660a363135303766316465343631376230386631373563643332373532373532
65363431646663613962336137633563353063316630626434353436393139376664346238333165
62633463623761623535323732366265646365623432306632333163353865623530353933666338
30643634336434666637643732653333366663373130373831316562353033376531646631643462
30393534393439653132643765316330373564666337353131643032356261376238393132633830
37666434363938346262663765346163326634616336646136303333323239343839
