---
- name: Configure Web Server (Nginx)
  hosts: my_local
  become: yes

  tasks:
    - name: 1. Update apt cache and Install Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
        force_apt_get: yes  # Ø¨ÙŠØ®Ù„ÙŠ Ø£Ù†Ø³ÙŠØ¨Ù„ ÙŠØ³ØªØ®Ø¯Ù… apt-get Ù…Ø¨Ø§Ø´Ø±Ø© ÙˆØ¯Ù‡ Ø£Ø¶Ù…Ù†

    - name: 2. Ensure Nginx is started and enabled
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: 3. Customize the Web Page
      copy:
        content: "<h1>Welcome to Seif's Automated Web Server! ðŸš€</h1>"
        dest: /var/www/html/index.nginx-debian.html
        mode: '0644'
