apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ivolve
  name: pod-reader
rules:
- apiGroups: [""] # "" تعني الـ core API group
  resources: ["pods"]
  verbs: ["get", "list"] # مسموح له يشوف بس
